# "Python Programming: An Introduction to Computer Science"
# by John Zelle, 3rd Ed.
# Chapter 1: Computers and Programs
# End-of-Chapter Exercises
#
# REVIEW QUESTIONS
#
# True/False
#1. Information that is stored and manipulated by computers is called data. T
#2. Since floating-point numbers are extremely accurate, they should generally be used instead of ints. F
#3. Operations like addition and subtraction are defined in the math library. Tx  F
#4. The number of possible arrangements of n items is equal to n!. Fx T
#5. The sqrt function computes the squirt of a number. F
#6. The float data type is identical to the mathematical concept of a real number. F
#7. Computers represent numbers using base-2 (binary) representations. T
#8. A hardware float can represent a larger range of values than a hardware int. Fx T 
#9. Type conversion functions such as float are a safe alternative to eval for getting a number as user input.T
#10. In Python, 4+5 produces the same result type as 4. 0+5. 0.  F
#
#Multiple Choice 
#1. Which of the following is not a built-in Python data type? C
#a) int b) float c) rational d) string 
#2. Which of the following is not a built-in operation? D
#a)+ b)% c) abs () d) sqrt
#3. In order to use functions in the math library, a program must include D
#a) a comment b) a loop c) an operator d) an import statement 
#4. The value of 4! is B
#a) 9 b) 24 c) 41 d) 120 
#5. The most appropriate data type for storing the value of pi is B
#a) int b) float c) irrational d) string 
#6. The number of distinct values that can be represented using 5 bits is C
#a) 5 b) 10 c) 32 d) 50 
#7. In a mixed-type expression involving ints and floats, Python will convert D?
#a) floats to ints b) ints to strings 
#c) both floats and ints to strings d) ints to floats 
#8. Which of the following is not a Python type-conversion function?D
#a) float b) round c) int d) abs
#9. The pattern used to compute factorials is A
#a) accumulator b) input, process, output 
#c) counted loop d) plaid 
#10. In modern Python, an int value that grows larger than the underlying hardware int D
#a) causes an overflow b) converts to float 
#c) breaks the computer d) uses more memory 
#

#Discussion 
#1. Show the result of evaluating each expression. Be sure that the value is in the proper form to indicate its type (int or float). If the expression is 
#illegal, explain why.
#								Expected value     |    Actual value
#a) 4.0 / 10.0 + 3.5 * 2         	          7.4  | 7.4
#b) 10 % 4 + 6 / 2								 5 | 5.0
#c) abs (4 - 20 // 3) **3						 8 | 8		
#d) sqrt (4.5 - 5.0) + 7 * 3	 math domain error | math domain error
#e) 3 * 10 // 3 + 10 % 3 						10 |11?
#f) 3 ** 3 										27 | 27

#2. Translate each of the following mathematical expressions into an equivalent Python expression. You may assume that the math library has been imported 
#(via import math). 
#  2. Translate each of the following mathematical expressions into an equivalent Python expression. You may assume that the math
#     library has been imported (via import math).
#     a) (3 + 4)(5)                    -> (3 + 4) * 5   
#     b) (n(n-1))/2                    -> (n * (n-1)) / 2    
#     c) 4pir^2                        -> 4 * math.pi *r ** 2    
#     d) sqrt(r(cosa)^2 + r(sinb)^2)   -> math.sqrt(r * (math.cos(a)) ** 2 + r * (math.sin(b) **2))
#     e) (y2 - y1) / (x2 - x1)         -> (y2 - y1) / (x2 - x1) 
#  3. Show the sequence of numbers that would be generated by each of the following range expressions.
#     a) range(5)                      -> [0, 1, 2, 3, 4]
#     b) range(3,5)                    -> [3, 4]
#     c) range(4,13,3)                 -> [4, 7, 10]
#     d) range(15,5,-2)                -> [15, 13, 11, 9, 7]
#     e) range(5,3)                    -> []
#
#  4. Show the output that would be generated by each of the following program fragments.
#								Expected value     |    Actual value
#
#     a) for i in range(1,11):	
#            print(i*i)
#													1
#													4  5
#													9  14
#													16 30
#													25  55
#													36  91
#													49  140
#													64   204
#													81   285
#													100  385
#
#     b) for i in [1,3,5,7,9]:
#            print(i, ":", i**3)
#        print(i)   
#
#													1 : 1
#													3 : 27
#													5 : 125
#													7 : 343
#													9 : 729
#													9 (print the end of the sequence the largest number of list]
#     c) x = 2
#        y = 10
#        for j in range(0, y, x):
#            print(j, end="")
#            print(x + y)
#       print("done")
#													012
#													212
#													412
#													612
#													812
#													done
#					
#     d) ans = 0
#        for i in range(1,11):
#            ans = ans + i*i
#            print(i)
#        print(ans)
#													1
#													2
#													3
#													...
#													10
#													385 (1+4+9+16+25+36+49+...+100)
#
##  5. What do you think will happen if you use a negative number as the second parameter in the round function? For example, what should be the result 
#	of round(314.159265, -1)? Explain the rational for your answer. After you've written your answer, consult the Python documentation or try out some
#   examples to see what Python actually does in this case.
#		Expected value| Actual value
#			314.15926 | 310.0
#
##  6. What do you think will happen when the operands to the integer division or remainder operations are negative? Consider each of the
#     following cases and try to predict the results. Then try them out in Python.
#     Hint: Recall the magic formula a = (a//b)(b) + (a%b).
#		    		Expected value| Actual value
#     a) -10 // 3				-4
#     b) -10 % 3				not -1 but -2->-12/3
#     c) 10 // -3				-4
#     d) 10 % -3				-2
#     e) -10 // -3				3
#
#### PROGRAMMING EXERCISES

#  1. Write a program to calculate the volume and surface area of a sphere from its radius, given as input. Here are some formulas that might
#     be useful:
#     V = (4/3)3pir^3
#     A = 4pir^2
#	
#
#





